services:
  jupyter-lab:
    image: tensorflow/tensorflow:2.13.0-gpu
    ports:
      - "8888:8888"
    volumes:
      - ../training:/training
    command:
      - /bin/sh
      - -c
      - |
        cd /training &&
        pip install --upgrade pip &&
        pip install --upgrade jupyterlab matplotlib pandas &&
        jupyter lab --ip=0.0.0.0 --allow-root --no-browser
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
